import React, { useState } from 'react';
import AppNavbar from './AppNavbar';
import { useAuth } from '../context/AuthContext';
import { useInterview } from '../context/InterviewContext';
import {
  IconSparkles as Sparkles,
  IconShieldCheck as ShieldCheck,
  IconFileText as FileText,
  IconCircleCheck as CheckCircle2,
  IconLock as Lock,
  IconTrash as Trash2,
  IconHelpCircle as HelpCircle,
  IconSend as Send,
  IconTrendingUp as TrendingUp,
  IconArrowRight as ArrowRight,
  IconChevronRight as ChevronRight,
  IconInfoCircle as Info,
  IconAlertTriangle as AlertTriangle,
  IconChartBar as BarChart3,
} from '@tabler/icons-react';

// ─────────────────────────────────────────────────────────────
// 1. HOW IT WORKS PAGE
// ─────────────────────────────────────────────────────────────
export function HowItWorksPage({ onNavigate }) {
  return (
    <div className="min-h-screen bg-[#0B0D13] text-slate-100 flex flex-col justify-between select-none font-sans">
      <AppNavbar currentActive="how-it-works" />

      <main className="max-w-4xl mx-auto w-full px-6 py-12 space-y-12 text-left flex-1">
        {/* Header */}
        <div className="space-y-4 border-b border-white/10 pb-8">
          <h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight text-white">
            How Evaluation Works
          </h1>
          <p className="text-base text-slate-400 leading-relaxed text-pretty">
            AI Interview Evaluator uses structured role rubrics and transparent scoring signals to provide objective practice feedback. Scores are coaching indicators designed to help you prepare.
          </p>
        </div>

        {/* 3-Step Process */}
        <section className="space-y-6">
          <h2 className="text-2xl font-extrabold text-white tracking-tight">The 3-Step Practice Workflow</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-[#131823] border border-white/10 p-6 rounded-3xl space-y-3 shadow-2xl">
              <div className="w-10 h-10 rounded-2xl bg-teal-950/80 border border-teal-500/30 flex items-center justify-center font-black font-mono text-teal-400 shadow-md">
                01
              </div>
              <h3 className="text-base font-bold text-white">Select Role & Format</h3>
              <p className="text-xs text-slate-400 leading-relaxed text-pretty">
                Configure your target level and choose from DSA, System Design, Bug Hunting, or HR Round.
              </p>
              <span className="text-[11px] font-mono text-teal-400/80 block pt-2">Duration: 5 – 60 min</span>
            </div>

            <div className="bg-[#131823] border border-white/10 p-6 rounded-3xl space-y-3 shadow-2xl">
              <div className="w-10 h-10 rounded-2xl bg-teal-950/80 border border-teal-500/30 flex items-center justify-center font-black font-mono text-teal-400 shadow-md">
                02
              </div>
              <h3 className="text-base font-bold text-white">Guided Simulation</h3>
              <p className="text-xs text-slate-400 leading-relaxed text-pretty">
                Answer realistic technical prompts using voice with live transcripts, text input, or code execution.
              </p>
              <span className="text-[11px] font-mono text-teal-400/80 block pt-2">Voice or Text-Only</span>
            </div>

            <div className="bg-[#131823] border border-white/10 p-6 rounded-3xl space-y-3 shadow-2xl">
              <div className="w-10 h-10 rounded-2xl bg-teal-950/80 border border-teal-500/30 flex items-center justify-center font-black font-mono text-teal-400 shadow-md">
                03
              </div>
              <h3 className="text-base font-bold text-white">Rubric-Based Breakdown</h3>
              <p className="text-xs text-slate-400 leading-relaxed text-pretty">
                Review structured Bar Raiser feedback on architecture trade-offs, code complexity, and edge cases.
              </p>
              <span className="text-[11px] font-mono text-teal-400/80 block pt-2">Detailed Report</span>
            </div>
          </div>
        </section>

        {/* Scoring Disclaimers */}
        <section className="bg-teal-950/40 border border-teal-500/30 p-6 rounded-3xl space-y-3">
          <h3 className="text-xs font-bold text-teal-400 uppercase tracking-wider font-mono flex items-center gap-1.5">
            <Info className="w-4 h-4" /> Scoring & Accuracy Disclaimer
          </h3>
          <p className="text-xs text-slate-300 leading-relaxed text-pretty">
            Feedback and numerical scores generated by this platform are automated practice signals. They do not constitute an official employment evaluation or hiring guarantee.
          </p>
        </section>

        {/* CTAs */}
        <div className="pt-4 flex gap-4">
          <button
            onClick={() => onNavigate('setup')}
            className="py-3.5 px-6 rounded-xl bg-gradient-to-r from-teal-500 to-emerald-400 text-slate-950 text-xs font-extrabold shadow-lg shadow-teal-500/20 transition-all active:scale-98 cursor-pointer flex items-center gap-2"
          >
            <span>Start a Mock Interview</span>
            <ArrowRight className="w-4 h-4" />
          </button>
          <button
            onClick={() => onNavigate('landing')}
            className="py-3.5 px-6 rounded-xl bg-[#171E2D] hover:bg-[#1E273A] border border-white/10 text-slate-200 text-xs font-semibold shadow-sm transition-all cursor-pointer"
          >
            Back to Home
          </button>
        </div>
      </main>

      <footer className="py-4 border-t border-white/10 bg-[#0E121B] text-center" />
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// 2. PRIVACY & DATA POLICY PAGE
// ─────────────────────────────────────────────────────────────
export function PrivacyPage({ onNavigate }) {
  const [dataDeleted, setDataDeleted] = useState(false);

  const handleClearData = () => {
    localStorage.clear();
    setDataDeleted(true);
    setTimeout(() => setDataDeleted(false), 4000);
  };

  return (
    <div className="min-h-screen bg-[#0B0D13] text-slate-100 flex flex-col justify-between select-none font-sans">
      <AppNavbar currentActive="privacy" />

      <main className="max-w-4xl mx-auto w-full px-6 py-12 space-y-10 text-left flex-1">
        <div className="space-y-3 border-b border-white/10 pb-8">
          <h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight text-white">
            Privacy Policy & Data Controls
          </h1>
          <p className="text-sm text-slate-400 leading-relaxed text-pretty">
            Your audio recordings, transcripts, uploaded resumes, and practice answers belong to you. We process audio solely to generate live transcripts and practice evaluations.
          </p>
        </div>

        <div className="space-y-8 text-xs sm:text-sm text-slate-300 leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">1. Audio & Speech Processing</h2>
            <p className="text-slate-400">
              Audio recordings are processed in real time to generate transcripts and speech pace estimates. Audio is never used to train public foundation models or sold to third-party advertisers.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">2. Local Storage & Data Retention</h2>
            <p className="text-slate-400">
              Your past interview scores, saved code drafts, and whiteboards are stored locally in your browser's local storage unless signed into a cloud session.
            </p>
          </section>

          <section className="space-y-3 bg-[#131823] border border-white/10 p-6 rounded-3xl shadow-2xl">
            <h2 className="text-base font-bold text-white">3. One-Click Data Deletion</h2>
            <p className="text-xs text-slate-400 pb-2">
              Want to purge all local interview history, cached transcripts, and saved settings from this device?
            </p>
            <button
              onClick={handleClearData}
              className="py-3 px-6 rounded-xl bg-rose-950/60 hover:bg-rose-900/60 border border-rose-500/40 text-rose-300 text-xs font-bold transition-all cursor-pointer shadow-sm flex items-center gap-1.5"
            >
              <Trash2 className="w-3.5 h-3.5" />
              <span>{dataDeleted ? '✓ All Data Cleared!' : 'Purge All My Saved Data Now'}</span>
            </button>
          </section>
        </div>
      </main>

      <footer className="py-4 border-t border-white/10 bg-[#0E121B] text-center" />
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// 3. TERMS OF SERVICE PAGE
// ─────────────────────────────────────────────────────────────
export function TermsPage({ onNavigate }) {
  return (
    <div className="min-h-screen bg-[#0B0D13] text-slate-100 flex flex-col justify-between select-none font-sans">
      <AppNavbar currentActive="terms" />

      <main className="max-w-4xl mx-auto w-full px-6 py-12 space-y-8 text-left flex-1">
        <div className="space-y-3 border-b border-white/10 pb-8">
          <h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight text-white">
            Terms of Service
          </h1>
          <p className="text-sm text-slate-400 leading-relaxed text-pretty">
            Terms governing your use of the AI Interview Evaluator practice platform.
          </p>
        </div>

        <div className="space-y-6 text-xs sm:text-sm text-slate-300 leading-relaxed">
          <section className="space-y-2">
            <h2 className="text-base font-bold text-white">1. Practice & Educational Purpose</h2>
            <p className="text-slate-400">
              AI Interview Evaluator is an educational tool designed to help candidate software engineers practice technical interview rounds. It does not warrant employment, job offers, or specific hiring outcomes with any third-party employer.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-white">2. Acceptable Use</h2>
            <p className="text-slate-400">
              Users agree not to attempt reverse-engineering internal sandbox APIs, executing malicious payloads, or abusing automated problem generation endpoints.
            </p>
          </section>
        </div>
      </main>

      <footer className="py-4 border-t border-white/10 bg-[#0E121B] text-center" />
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// 4. SECURITY & SANDBOX POLICY PAGE
// ─────────────────────────────────────────────────────────────
export function SecurityPage({ onNavigate }) {
  return (
    <div className="min-h-screen bg-[#0B0D13] text-slate-100 flex flex-col justify-between select-none font-sans">
      <AppNavbar currentActive="security" />

      <main className="max-w-4xl mx-auto w-full px-6 py-12 space-y-8 text-left flex-1">
        <div className="space-y-3 border-b border-white/10 pb-8">
          <h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight text-white">
            Security Architecture & Code Sandboxing
          </h1>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs text-slate-300">
          <div className="bg-[#131823] border border-white/10 p-6 rounded-3xl space-y-2 shadow-2xl">
            <h2 className="text-sm font-bold text-white flex items-center gap-1.5">
              <ShieldCheck className="w-4 h-4 text-teal-400" />
              <span>Isolated Sandbox Execution</span>
            </h2>
            <p className="text-slate-400 leading-relaxed">
              Code submitted in the DSA and Bug Hunter studios runs inside strict isolated execution environments with CPU timeouts, memory caps, and no internal network access.
            </p>
          </div>

          <div className="bg-[#131823] border border-white/10 p-6 rounded-3xl space-y-2 shadow-2xl">
            <h2 className="text-sm font-bold text-white flex items-center gap-1.5">
              <Lock className="w-4 h-4 text-teal-400" />
              <span>Encrypted Transit</span>
            </h2>
            <p className="text-slate-400 leading-relaxed">
              All communications between your browser and our evaluation servers are encrypted using TLS 1.3 encryption.
            </p>
          </div>
        </div>
      </main>

      <footer className="py-4 border-t border-white/10 bg-[#0E121B] text-center" />
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// 5. ACCESSIBILITY STATEMENT PAGE (WCAG 2.2 AA)
// ─────────────────────────────────────────────────────────────
export function AccessibilityPage({ onNavigate }) {
  return (
    <div className="min-h-screen bg-[#0B0D13] text-slate-100 flex flex-col justify-between select-none font-sans">
      <AppNavbar currentActive="accessibility" />

      <main className="max-w-4xl mx-auto w-full px-6 py-12 space-y-8 text-left flex-1">
        <div className="space-y-3 border-b border-white/10 pb-8">
          <h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight text-white">
            Accessibility Statement
          </h1>
          <p className="text-sm text-slate-400 leading-relaxed text-pretty">
            We are dedicated to ensuring that AI Interview Evaluator is accessible to engineers of all abilities, adhering to WCAG 2.2 Level AA guidelines.
          </p>
        </div>

        <div className="space-y-6 text-xs sm:text-sm text-slate-300 leading-relaxed">
          <div className="bg-[#131823] border border-white/10 p-6 rounded-3xl space-y-3 shadow-2xl">
            <h2 className="text-base font-bold text-white">Key Accessibility Features</h2>
            <ul className="list-disc list-inside space-y-2 text-slate-400">
              <li><strong>Keyboard Navigation:</strong> Complete interactive control via <kbd className="px-2 py-0.5 bg-[#0D111A] border border-white/10 rounded-lg font-mono text-xs text-teal-300">Tab</kbd>, <kbd className="px-2 py-0.5 bg-[#0D111A] border border-white/10 rounded-lg font-mono text-xs text-teal-300">Enter</kbd>, and <kbd className="px-2 py-0.5 bg-[#0D111A] border border-white/10 rounded-lg font-mono text-xs text-teal-300">Escape</kbd>.</li>
              <li><strong>Screen Reader Support:</strong> Explicit <code className="font-mono text-teal-300 bg-teal-950/80 border border-teal-500/30 px-1.5 py-0.5 rounded">aria-expanded</code>, <code className="font-mono text-teal-300 bg-teal-950/80 border border-teal-500/30 px-1.5 py-0.5 rounded">aria-controls</code>, and semantic landmarks.</li>
              <li><strong>Text-Only Fallback:</strong> Full practice suite available without microphone requirements.</li>
              <li><strong>Reduced Motion:</strong> Respects system <code className="font-mono text-teal-300 bg-teal-950/80 border border-teal-500/30 px-1.5 py-0.5 rounded">prefers-reduced-motion</code> settings.</li>
            </ul>
          </div>
        </div>
      </main>

      <footer className="py-4 border-t border-white/10 bg-[#0E121B] text-center" />
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// 6. SUPPORT & HELP DESK PAGE
// ─────────────────────────────────────────────────────────────
export function SupportPage({ onNavigate }) {
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = (e) => {
    e.preventDefault();
    setSubmitted(true);
  };

  return (
    <div className="min-h-screen bg-[#0B0D13] text-slate-100 flex flex-col justify-between select-none font-sans">
      <AppNavbar currentActive="support" />

      <main className="max-w-4xl mx-auto w-full px-6 py-12 space-y-8 text-left flex-1">
        <div className="space-y-3 border-b border-white/10 pb-8">
          <h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight text-white">
            Support & Candidate Help Desk
          </h1>
          <p className="text-sm text-slate-400 leading-relaxed text-pretty">
            Have questions about evaluation rubrics or need assistance with audio setup?
          </p>
        </div>

        <div className="max-w-lg bg-[#131823] border border-white/10 p-6 sm:p-8 rounded-3xl space-y-4 shadow-2xl">
          {submitted ? (
            <div className="p-4 bg-emerald-950/60 border border-emerald-500/40 text-emerald-300 rounded-2xl font-bold text-xs flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-emerald-400 flex-shrink-0" />
              <span>Thank you! Your support request has been submitted. Our engineering team will respond shortly.</span>
            </div>
          ) : (
            <form onSubmit={handleSubmit} className="space-y-4 text-xs">
              <div>
                <label className="block text-slate-300 font-bold mb-1 font-mono">Your Email</label>
                <input
                  type="email"
                  required
                  placeholder="candidate@techcompany.com"
                  className="w-full bg-[#0D111A] border border-white/10 rounded-xl p-3 text-white placeholder-slate-500 focus:outline-none focus:border-teal-400"
                />
              </div>

              <div>
                <label className="block text-slate-300 font-bold mb-1 font-mono">Message or Issue Description</label>
                <textarea
                  required
                  rows={4}
                  placeholder="Describe your issue or question..."
                  className="w-full bg-[#0D111A] border border-white/10 rounded-xl p-3 text-white placeholder-slate-500 focus:outline-none focus:border-teal-400"
                />
              </div>

              <button
                type="submit"
                className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-emerald-400 text-slate-950 font-extrabold rounded-xl transition-all active:scale-98 cursor-pointer shadow-lg shadow-teal-500/20 flex items-center justify-center gap-1.5"
              >
                <span>Send Support Message</span>
                <Send className="w-3.5 h-3.5" />
              </button>
            </form>
          )}
        </div>
      </main>

      <footer className="py-4 border-t border-white/10 bg-[#0E121B] text-center" />
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// 7. ANALYTICS & PROGRESS DASHBOARD PAGE
// ─────────────────────────────────────────────────────────────
export function AnalyticsPage({ onNavigate }) {
  const { user, history } = useAuth();
  const { viewPastReport } = useInterview();
  const userHistory = Array.isArray(history) ? history : [];
  const completedCount = userHistory.length;

  const dsaCount = userHistory.filter((h) => (h.module || h.type || '').toLowerCase().includes('dsa')).length;
  const sysDesignCount = userHistory.filter((h) => (h.module || h.type || '').toLowerCase().includes('system') || (h.module || '').toLowerCase().includes('design')).length;
  const bugHuntCount = userHistory.filter((h) => (h.module || h.type || '').toLowerCase().includes('bug')).length;

  return (
    <div className="min-h-screen bg-[#080C10] text-slate-100 flex flex-col justify-between select-none font-sans">
      <AppNavbar currentActive="analytics" />

      <main className="max-w-5xl mx-auto w-full px-6 py-12 space-y-8 text-left flex-1">
        <div className="space-y-3 border-b border-slate-800/80 pb-8 flex items-center justify-between flex-wrap gap-4">
          <div>
            <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-white">
              Score Analytics & Practice History
            </h1>
            <p className="text-xs text-slate-400 mt-1">
              {user?.name ? `Logged in as ${user.name}` : 'Track your mock interview evaluations and module practice records.'}
            </p>
          </div>
          <button
            onClick={() => onNavigate('setup')}
            className="py-3 px-6 rounded-full bg-gradient-to-r from-teal-400 to-emerald-400 text-slate-950 text-xs font-extrabold shadow-[0_0_20px_rgba(45,212,191,0.3)] hover:shadow-[0_0_25px_rgba(45,212,191,0.5)] transition-all active:scale-95 cursor-pointer flex items-center gap-2"
          >
            <span>Start New Mock Session</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>

        {/* Practice Module Breakdown */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-5 text-xs">
          <div className="bg-slate-900/60 border border-slate-800/80 p-6 rounded-2xl space-y-2 shadow-xl backdrop-blur-md">
            <span className="text-slate-400 font-mono">DSA Practice</span>
            <p className="text-2xl font-black text-emerald-400 font-mono">
              {dsaCount > 0 ? `${dsaCount} Sessions` : '0 Sessions'}
            </p>
            <p className="text-[11px] text-slate-500">
              {dsaCount > 0 ? 'Live coding challenges recorded' : 'No DSA challenges completed yet'}
            </p>
          </div>

          <div className="bg-slate-900/60 border border-slate-800/80 p-6 rounded-2xl space-y-2 shadow-xl backdrop-blur-md">
            <span className="text-slate-400 font-mono">Mock Interviews</span>
            <p className="text-2xl font-black text-teal-400 font-mono">
              {completedCount > 0 ? `${completedCount} Completed` : '0 Completed'}
            </p>
            <p className="text-[11px] text-slate-500 font-mono">
              {completedCount > 0 ? 'Full multi-round evaluations' : 'Ready to start first simulation'}
            </p>
          </div>

          <div className="bg-slate-900/60 border border-slate-800/80 p-6 rounded-2xl space-y-2 shadow-xl backdrop-blur-md">
            <span className="text-slate-400 font-mono">Bug Hunting</span>
            <p className="text-2xl font-black text-amber-400 font-mono">
              {bugHuntCount > 0 ? `${bugHuntCount} Audits` : '0 Audits'}
            </p>
            <p className="text-[11px] text-slate-500 font-mono">
              {bugHuntCount > 0 ? 'Code audits analyzed' : 'No debugging labs completed yet'}
            </p>
          </div>
        </div>

        {/* Evaluation Records */}
        <section className="space-y-4 pt-4">
          <h2 className="text-lg font-bold text-white">Recent Evaluation Records</h2>

          {completedCount === 0 ? (
            <div className="p-10 text-center space-y-4 bg-slate-900/60 border border-slate-800/80 rounded-2xl shadow-xl backdrop-blur-md">
              <div className="w-14 h-14 rounded-2xl bg-teal-500/10 border border-teal-500/30 flex items-center justify-center text-teal-400 mx-auto shadow-md">
                <BarChart3 className="w-7 h-7" />
              </div>
              <div className="space-y-1.5 max-w-md mx-auto">
                <h3 className="text-base font-extrabold text-white">No Evaluation Records Yet</h3>
                <p className="text-xs text-slate-400 leading-relaxed">
                  Your account was created today. Complete a full mock interview or practice in one of our targeted studios to begin tracking your performance signals and rubrics.
                </p>
              </div>
              <div className="pt-2">
                <button
                  type="button"
                  onClick={() => onNavigate('setup')}
                  className="rounded-full px-6 py-3 bg-gradient-to-r from-teal-400 to-emerald-400 text-slate-950 text-xs font-extrabold shadow-[0_0_20px_rgba(45,212,191,0.3)] hover:shadow-[0_0_25px_rgba(45,212,191,0.45)] transition-all active:scale-95 cursor-pointer inline-flex items-center gap-2"
                >
                  <span>Start Your First Interview</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          ) : (
            <div className="overflow-x-auto border border-slate-800/80 rounded-2xl bg-slate-900/60 shadow-xl backdrop-blur-md">
              <table className="w-full text-left text-xs font-mono">
                <thead className="bg-[#0B0F14] text-slate-400 uppercase text-[10px] border-b border-slate-800/80">
                  <tr>
                    <th className="p-4">Date</th>
                    <th className="p-4">Module / Track</th>
                    <th className="p-4">Role Level</th>
                    <th className="p-4">Score / Decision</th>
                    <th className="p-4">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/50 text-slate-300">
                  {userHistory.map((item, idx) => {
                    const displayScore = item.overallScore !== undefined && item.overallScore !== null
                      ? `${item.overallScore}%`
                      : (item.hiringDecision || 'Completed');
                    return (
                      <tr key={idx} className="hover:bg-white/5 transition-colors">
                        <td className="p-4 text-slate-400">{item.date ? new Date(item.date).toLocaleDateString() : 'Today'}</td>
                        <td className="p-4 text-white font-bold">{item.targetRole || item.module || 'Mock Interview'}</td>
                        <td className="p-4 text-teal-400">{item.difficultyLevel || 'Standard'}</td>
                        <td className="p-4 font-bold text-emerald-400">
                          {displayScore}
                        </td>
                        <td className="p-4">
                          <button
                            onClick={() => viewPastReport(item)}
                            className="text-teal-400 hover:text-teal-300 cursor-pointer flex items-center gap-1 font-sans font-bold hover:underline"
                          >
                            <span>Review</span>
                            <ChevronRight className="w-3 h-3" />
                          </button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </section>
      </main>

      <footer className="py-4 border-t border-slate-800/80 bg-[#080C10] text-center" />
    </div>
  );
}

